@startuml "Instrutor"
left to right direction

actor "Instrutor" as instrutor


rectangle "MCU02 - Instrutor"{
    usecase "Cadastrar Treino" as cadastrar_treino
    usecase "Visualizar Treino" as visualizar_treino
    usecase "Atualizar Treino" as atualizar_treino
    usecase "Remover Treino" as remover_treino
    usecase "Cadastrar Carga" as cadastrar_carga
    usecase "Atualizar Carga" as atualizar_carga
    usecase "Buscar Cliente" as buscar_cliente
    usecase "Visualizar Cliente" as visualizar_cliente
    usecase "Cadastrar Avaliação" as cadastrar_avaliacao
    usecase "Visualizar Avaliação" as visualizar_avaliacao
    usecase "Atualizaar Avaliação" as atualizar_avaliacao
    usecase "Visualizar Notificações" as visualizar_notificacoes

}

instrutor -- buscar_cliente
buscar_cliente <.. visualizar_cliente: <<extend>>
visualizar_cliente <.. cadastrar_treino: <<extend>>
visualizar_cliente <.. atualizar_treino: <<extend>>
visualizar_cliente <.. remover_treino: <<extend>>
visualizar_cliente <.. visualizar_treino: <<extend>>
atualizar_treino <.. atualizar_carga: <<extend>>
cadastrar_treino ..> cadastrar_carga: <<include>>
instrutor -- visualizar_notificacoes: <<extend>>
visualizar_cliente <.. cadastrar_avaliacao: <<extend>>
visualizar_cliente <.. atualizar_avaliacao: <<extend>>
visualizar_cliente <.. visualizar_avaliacao: <<extend>>


@enduml